/*
 * Copyright 2020 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

const bo = [
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/bienestar-la-reduccion-calorica-en-nuestras-bebidas-es-la-prioridad-del-n' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/ecoladrillos-para-viviendas-sustentables--el-sueno-de-david-para' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/bienestar-conoce-como-trabaja-el-centro-de-innovacion' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/bienestar-de-la-f-brica-a-la-mesa-coca-cola-apuesta-por-las-compras-online-y-el-delivery-seguro-con-su-nueva-plataforma-de-ventas' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-asi-funcionan-los-acuerdos-reciprocos-por-agua-que-salvan-bosques' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-coca-cola-renueva-su-compromiso-con-bolivia-en-su-196-aniversari' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-el-compromiso-por-unmundosinresiduos-suma-nuevos-aliados-en-lago-titicaca' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-el-primer-concurso-de-poesia-sobre-reciclaje-ya-tiene-ganadora' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-conocemos-a-claudia--la-primera-chofer-de-coca-cola-bolivia-' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-la-plataforma-de-educacion-ambiental-re-crea-ya-capacito-a-1-200' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/impacto-socio-economico' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-coca-cola-bolivia-suma-una-nueva-alianza-para-avanzar-en-el-cami' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-coca-cola-bolivia-refuerza-su-compromiso-por-un-mundo-sin-residuos-con-la-botella-de-vital-hecha-100-de-otras-botellas' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-por-qu-decirle-que-s-a-las-botellas-retornables-la-respuesta-est-en-las-cuatro-r-de-la-retornabilidad' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-fundacion-ellen-macarthur--los-plasticos-dentro-de-la-economia-y' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-este-22-de-marzo-reafirmamos-nuestro-compromiso-con-el-cuidado-d' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-nuestro-compromiso--optimizar-el-uso-de-agua' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-emprendedoras-bolivianas-se-capacitan-para-mejorar-sus-negocios' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-objetivo-logrado-coca-cola-bolivia-celebra-la-participaci-n-de-m-s-de-4-000-emprendedores-en-los-programas-gerente-pyme' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-_semilla-capital-2-0-ipara-crecer-juntos--llegaa-a-ocho-ciudades' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-la-fundacion-coca-cola-llego-a-u-s1-000-millones-en-donaciones' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/-salteneria-chingola---tradicion-familiar-atras-de-la-empanada-r' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/fundacion-coca-cola-de-bolivia-recibe-el--reconocimiento-a-la-re' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/la-red-de-contenedores-para-reciclar-llego-a-mercados-y-centros-' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/conexiones--la-exposicion-fotografica-que-enaltece-el-trabajo-de' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/te-contamos-la-rica-historia-detras-de-la-saltena--este-simbolo-' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/foro-latinoamericano-de-economia-circular--compartimos-los-avanc' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/seguimos-acompanando-a-las-emprendedoras-bolivianas--800-mujeres' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/-la-navidad-es-magica-cuando-la-compartimos---conoce-la-campana-' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-sabor-y-tradicion--el-exito-detras-del-restaurante-la-le-li-lo-l' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-nos-sumamos-a-la-campana-global-de-plan-international-para-empod' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-la-cocina-de-_aurorita-nos-abre-sus-puertas-y-devela-el-secreto-' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-elmejorregaloserest-conoce-a-los-emboluntarios-que-alegraron-las-fiestas-a-los-ni-os-del-hogar-francisca-risci' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-juntossalimosadelante-trabajadores-de-cuatro-hospitales-de-bolivia-recibieron-donaciones-de-equipos-de-bioseguridad' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-coca-cola-bolivia-y-pnud-renuevan-su-alianza-para-apoyar-la-reac' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-la-salte-er-a-jet-set-tradici-n-cultura-y-una-invitaci-n-a-hacer-especial-cualquier-d-a-de-la-semana' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-tienen-tres-restaurantes-a-cargo-y-enfrentaron-la-pandemia-a-fue' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-animate-a-preparar-compost-casero-con-cuatro-sencillos-pasos-' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-primitivo-quispe--el-guia-que-suena-con-seguir-amaneciendo-entre' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-liliana-emprendedora-de-calidad-a-los-21-a-os-abri-su-propia-tienda-y-hoy-se-capacita-para-hacer-crecer-su-negocio' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-san-felix-cuida-su-tesoro-mas-preciado-y-mejora-el-acceso-a-agua' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-dannya--la-sonadora-que-construyo-de-cero-su-propio-micromercado' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-san-jacinto-se-convierte-en-un-modelo-de-gestion-de-agua-en-la-r' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-basilia-lidera-el-negocio-turistico-familiar-y-cuida-los-bosques' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-diez-nuevos-contenedores-para-botellas-pet-dan-nuevo-impulso-al-' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-ser-transparente-para-ser-m-s-verde-sprite-clear-m-s-amigable-con-el-ambiente' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-el-reciclaje-y-la-solidaridad-se-alian-en-tarija-de-la-mano-de-v' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-los-contenedores-de-reciclaje-de-vital-llegan-a-mas-ciudades-de-' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-los-envases-de-pet-transparente--aliados-en-la-industria-de-la-e' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-primitivo-quispe--el-guia-que-suena-con-seguir-amaneciendo-entre1' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/bienestar-fanta-se-vuelve-loca-de-colores-para-desterrar-los-dias-grises' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/retornar-en-algo-mejor--el-nuevo-comercial-de-coca-cola-que-insp' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-agrupaciones-de-recolectores-reciben-nueve-flamantes-motocarros-' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-lonas-publicitarias-recicladas-se-convierten-en-ecobolsos-' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-alfabeto--la-divertida-propuesta-de-coca-cola-para-que-compartas' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-te-presentamos-a-la-multifac-tica-karina-recolectora-l-der-gremial-y-madre-de-cinco-hijos' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-lasmujerestransforman-acompa-amos-el-desarrollo-econ-mico-de-5-millones-de-mujeres-y-renovamos-nuestro-compromiso' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-luchadora-y-comprometida-te-presentamos-a-mar-a-teresa-la-mujer-que-lidera-la-fundaci-n-natura-y-transforma-su-comunidad' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-lasmujerestransforman-j-venes-y-preparadas-el-nuevo-perfil-de-la-emprendedora-boliviana' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/-lasmujerestransforman-para-crear-un-mundo-mejor' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-nuestro-homenaje-a-los-padres-emprendedores--que-con-su-fuerza-y' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-alejandro-soto-un-agricultor-comprometido-con-el-planeta-y-sus-vecinos-ofreci-la-vertiente-que-nace-en-sus-tierras-para-abastecer-de-agua-a-la-comunidad' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-las-fabricas-de-agua-de-la-fundacion-natura-son-reconocidas-mund' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-un-mundo-sin-residuos-los-contenedores-de-reciclaje-de-vital-llegan-a-sucre' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-empacar-suma-energia-solar-a-su-planta-de-reciclaje-y-se-consoli' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-los-contenedores-de-reciclaje-de-vital-llegan-a-las-provincias-d' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-detr-s-de-la-idea-conocemos-a-los-creativos-responsables-de-la-nueva-campa-a-de-coca-cola-bolivia-que-promueve-los-envases-retornables' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/el-esp-ritu-del-compromiso-por-un-unmundosinresiduos-desembarca-en-el-lago-uru-uru-de-oruro' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-los-contenedores-de-reciclaje-de-vital-llegan-a-estaciones-de-se' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-santa-cruz-impulsa-el-reciclaje-y-el-trabajo-de-los-recolectores' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-encuentro-de-intercambio-verde-una-experiencia-para-unir-esfuerzos-por-unmundosinresiduos' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-recolectores-de-santa-cruz-reciben-compactadoras-de-botellas-y-c' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad------_la-casona_--el-restaurante-familiar-que-celebra-el-apoyo-d' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-d-a-de-la-tierra-2021-reafirmamos-nuestro-trabajo-en-el-cuidado-del-planeta' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-daniela--la-especialista-medioambiental-que-busca-empoderar-a-lo' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-claudia--la-chofer-de-coca-cola-que-con-su-tiktok-ayuda-a-cuidar' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-cuidar-al-medio-ambiente-impulsar-a-las-mujeres-y-trabajar-junto-a-las-comunidades-los-hitos-de-los-78-a-os-de-coca-cola-bolivia' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/coca-cola-bolivia-junto-a-la-fundacion-alalay-y-los-restaurantes-del-pais-se-unen' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-conocemos-a-los-vecinos-del-condominio-vittoria--un-ejemplo-en-e' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-cleider-y-ciro-recolectores-de-base-es-una-emoci-n-ayudar-a-que-nuestro-hijo-cumpla-su-sue-o-de-ser-piloto' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-te-invitamos-a-conocer-el-proyecto-recrea--nuestra-iniciativa-pa' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-mas-de-120-trabajadores-de-la-embotelladora-embol-celebraron-el-' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-dise-o-ecol-gico-y-solidario-transforman-lonas-publicitarias-recicladas-en-impermeables-para-personas-sin-hogar' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/productos-la-nueva-coca-cola-sin-az-car-llega-a-bolivia-con-un-desaf-o-es-la-mejor-coca-cola-de-todas' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-el-periodismo-verde-gana-terreno-conocemos-el-trabajo-de-la-uni-n-de-periodistas-ambientales-de-bolivia' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-se-presento-latitud-r--la-plataforma-que-busca-transformar-la-ge' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-sumate-al-desafio-retornable-y-cuida-el-planeta-' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-puerta-a-puerta-por-un-mundo-sin-residuos-recolectores-de-santa-cruz-entusiasman-a-los-vecinos-para-impulsar-el-reciclaje' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-seis-de-cada-diez-bolivianos-ya-eligen-sus-bebidas-favoritas-en-botellas-retornables-conoce-por-qu-y-s-mate-t-tambi-n' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-y-si-por-cada-comida-que-compras-pudieras-donar-otra-para-algui' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-veronica-virreira-resignifica-el-plastico-de-descarte-y-los-tran' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-retornables-y-recuperaci-n-de-envases-coca-cola-bolivia-y-su-compromiso-con-la-econom-a-circular' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-reciclaje-y-compostaje--los-dos-caminos-para-contribuir-desde-ca' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/historia-rogelio--el-sonador-que-paso-de-ayudante-a-propietario-de-dos-ca' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-superior-taste-award-2021-vital-fue-catalogada-como-sobresaliente-por-un-jurado-de-200-chefs-y-sommeliers' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente--los-que-vivimos-del-campo-sabemos-la-importancia-del-agua-y-la-' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidadnos-sumamos-a-la-campana-ninas-con-igualdad' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-mas-de-100-familias-de-los-yungas-tendran-acceso-a-agua-potable-' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-coca-cola-y-el-agua-en-am-rica-latina-cuando-las-personas-se-sienten-parte-de-la-soluci-n-todo-toma-fuerza' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-el-compromiso-por-el-medio-ambiente-volvio-a-unir-a-los-trabajad' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad--_mi-sueno-era-tener-esta-casa-de-huespedes--te-presentamos-a-ma' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-emprendedores-turisticos-de-tihuanaco-apuestan-por-la-biosegurid' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-fundacion-coca-cola-suma-su-apoyo-para-que-1-100-hogares-del-pai' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-el-compromiso-por-unmundosinresiduos-se-suma-a-la-expocruz-la-feria-m-s-importante-de-bolivia' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-expocruz-2021--un-gran-espacio-de-reencuentro-para-promover-la-r' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-objetivo-cumplido-1-000-contenedores-de-reciclaje-de-vital-ya-est-n-instalados-en-diferentes-puntos-de-bolivia' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/juntos-para-algo-mejor-el-mensaje-de-coca-cola-para-ver-el-mundo-com-optimismo' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-el-alto--pando-y-beni-se-suman-a-la-red-de-contenedores-de-recic' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-en-el-dia-de-la-mujer-boliviana--celebramos-a-aquellas-que-lider' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-los-contenedores-de-reciclaje-de-vital-son-un-xito-en-las-estaciones-de-servicio-de-santa-cruz-recolectan-1-200-kilos-de-botellas-al-mes' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-la-escuela-de-los-acuerdos-reciprocos-por-agua-capacita-a-repres' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-las-familias-de-miraflores--guardianas-de-los-bosques--se-encami' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/iliana-reza--vicepresidente-de-operaciones-de-coca-cola-para-el-' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/cuidar-el-agua-y-mejorar-su-acceso-en-comunidades-rurales-de-bol' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/el-2021--un-ano-en-el-que-juntos-logramos-grandes-avances-en-el-' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/jenny--un-ejemplo-de-pujanza-al-frente-de-su-emprendimiento-gast' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/repasemos-juntos-nuestro-trabajo-de-2021--un-ano-lleno-de-desafi' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/pacto-global-reconoce-nuestras-buenas-practicas-en-materia-de-de' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/cuidar-el-agua-y-mejorar-su-acceso-en-comunidades-rurales-de-bol0' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/el-2021--un-ano-en-el-que-juntos-logramos-grandes-avances-en-el-0' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-se-presento-latitud-r--la-plataforma-que-busca-transformar-la-ge1' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-sumate-al-desafio-retornable-y-cuida-el-planeta-1' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/gerente-pyme-y-semilla-capital-volvieron-a-hacer-la-diferencia-p' },
  { URL: 'https://www.coca-coladebolivia.com.bo/novedades/ecoladrillos-para-viviendas-sustentables--el-sueno-de-david-para' },
];

const cl = [
  // { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-_los-fi_--artistas-multifaceticos-con-consciencia-ambiental-' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-sonadores-con-consciencia-en-el-lago-llanquihue' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-fundador-de-triciclos-es-el-champion-de-la-cop-25' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-coca-cola-firma-el-primer-pacto-por-los-plasticos-de-america' },
// { URL: 'https://www.cocacoladechile.cl/novedades/bienestar-samuel-dur-n-nutricionista-que-las-bebidas-hayan-transitado-al-edulcorante-es-una-excelente-adaptaci-n' },
// { URL: 'https://www.cocacoladechile.cl/novedades/historia-tesoros-de-coca-cola-en-vicuna' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-ensenar-en-terreno-a-vivir-sin-basura' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-jovenes-aprenden-a-reciclar-en-puerto-varas' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-betty-orgullosa-almacenera-de-achao-no-me-ir-a-a-otro-lugar' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-las-ambiciosas-metas-de-reciclaje-de-la-ley-rep' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-cocinar-con-el-sol-en-el-valle-del-elqui' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-un-panel-de-mujeres-transformadoras' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-futbol-mas-deporte-sin-fronteras' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-un-historico-almacen-en-cerro-alegre' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-futbol-mas-con-todo-este-2019' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-pioneras-del-reciclaje' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-soledad-mella--la-reina-del-reciclaje' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-inclusi-n-femenina-el-desaf-o-digital' },
// { URL: 'https://www.cocacoladechile.cl/novedades/desde-un-almacen-santa-olga-se-levanta' },
// { URL: 'https://www.cocacoladechile.cl/novedades/historias-ninos-y-ninas-dominan-la-pelota-por-igual' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-que-tienen-en-comun-un-zapatero--un-costurero-y-un-reparador-de' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-marta-zapata-almacenera-cuando-crece-este-negocio-crece-una-familia-y-crece-chile' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-alto-tarapaca-supera-su-meta' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-arica-a-putre-ruta-altiplano' },
// { URL: 'https://www.cocacoladechile.cl/novedades/pasos-para-un-reciclaje-limpio-y-exitoso-en-casa' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-eduardo-sanhueza-el-chileno-que-ha-estado-en-todas-las-cop' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-plastic-oceans--un-aliado-en-el-pacto-por-los-plasticos' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-educacion-ambiental-en-pleno-valle-del-elqui' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-y-si-el-plastico-no-fuera-nunca-mas-un-residuo-' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-escolares-de-valparaiso--pequenos-agentes-de-cambio' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-Empaques-Sustentables-alfombras-multicolores-a-partir-de-botellas-pet' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-reforestar--una-forma-efectiva-de-recuperar-el-agua' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-pet-100-reciclable' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-botella-nica-vivir-m-s-retornable' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-and-the-winner-is-itriciclos-' },
// { URL: 'https://www.cocacoladechile.cl/novedades/historias-chao-al-plastico-' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-actitud-re-no-se-detiene--iseguimos-en-2019-0' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-escuela-lipangue-de-lampa--re-campeones' },
// { URL: 'https://www.cocacoladechile.cl/novedades/historias-retornabilidad-y-economia-circular' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-la-reutilizacion-y-reciclaje-de-las-gigantografias-publicitarias' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-el-ecodiseno--clave-en-coca-cola' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-el-paso-a-paso-en-el-reciclaje-de-una-botella-de-pet' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-el-almacen-donde-los-clientes-prefieren-retornables' },
// { URL: 'https://www.cocacoladechile.cl/novedades/ejemplar-patrulla-medioambiental-universitaria' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-actitud-re-ya-contagio-a-todo-chile' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-guia-para-un-comprador-sustentable' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-las-lecciones-medioambientales-del-premio-nacional-de-ciencias' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-el-decalogo-del-pet' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-guillermo-gonz-lez-lleg-el-momento-de-la-econom-a-circular' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-bea-johnson--guru-de-la-cultura-basura-cero--estuvo-en-chile' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-la-familia-que-hace-volantines-con-bolsas-recicladas-' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-el-abc-de-la-ley-rep' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-la-innovadora-herramienta-que-reutiliza-las-botellas-plasticas' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-sembrar-para-recuperar-el-agua' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-se-puede-vivir-sin-producir-basura-' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-envases-mas-livianos-mejoran-su-huella' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-jos-miranda-el-reciclaje-es-el-sustento-de-nuestro-hogar' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-los-siete-tipos-de-pl-stico-del-m-s-al-menos-reciclable' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medioambiente-un-nuevo-ano-para-el-bus-del-reciclaje' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-el-padre-de-la-economia-circular-visito-chile' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-pablo-badenier-la-mejor-basura-es-la-que-no-se-genera' },
// { URL: 'https://www.cocacoladechile.cl/novedades/bienestar-ia-cocinar-con-ades-' },
// { URL: 'https://www.cocacoladechile.cl/novedades/bienestar-sommelier-marcelo-pino-en-chile-reci-n-estamos-aprendiendo-a-tomar-agua' },
{ URL: 'https://www.cocacoladechile.cl/novedades/bienestar-el-exitoso-primer-ano-de-coca-cola-sin-azucar' },
// { URL: 'https://www.cocacoladechile.cl/novedades/bienestar-siempre-innovando-cada-vez-menos-sellos' },
// { URL: 'https://www.cocacoladechile.cl/novedades/bienestar-sabor--bienestar-y-nada-de-azucar' },
// { URL: 'https://www.cocacoladechile.cl/novedades/bienestar-Acesulfame-K,-siempre-bien-acompanado' },
// { URL: 'https://www.cocacoladechile.cl/novedades/bienestar-el-endulzante-no-calorico-azucar' },
// { URL: 'https://www.cocacoladechile.cl/novedades/bienestar-un-minuto-aprender-aspartame' },
// { URL: 'https://www.cocacoladechile.cl/novedades/bienestar-ingesta-diaria-admisible' },
// { URL: 'https://www.cocacoladechile.cl/novedades/bienestar-smartwater-agua-inspirada-en-las-nubes' },
// { URL: 'https://www.cocacoladechile.cl/novedades/productos-la-roja-femenina-ya-tiene-su-bus' },
// { URL: 'https://www.cocacoladechile.cl/novedades/innovacion-ya-aprendiste-a-comprar-en-micoca-cola-cl-' },
// { URL: 'https://www.cocacoladechile.cl/novedades/los-nuevos-integrantes-de-la-familiay-nada' },
// { URL: 'https://www.cocacoladechile.cl/novedades/productos-coca-cola-y-guallarauco-uni-n-perfecta' },
// { URL: 'https://www.cocacoladechile.cl/novedades/productos-los-40-anos-de-kapo--el-sabor-animado' },
// { URL: 'https://www.cocacoladechile.cl/novedades/productos-festigame--un-fin-de-semana-inolvidable-' },
// { URL: 'https://www.cocacoladechile.cl/novedades/productos-fanaticos-de-coca-cola-y-sus-mas-grandes-tesoros' },
// { URL: 'https://www.cocacoladechile.cl/novedades/products-por-que-son-redondas-las-latas' },
// { URL: 'https://www.cocacoladechile.cl/novedades/products-nueva-botella-fanta' },
// { URL: 'https://www.cocacoladechile.cl/novedades/innovacion-vital-de-chanqueahue--el-origen-noble-del-agua-mineral' },
// { URL: 'https://www.cocacoladechile.cl/novedades/innovacion-la-atenci-n-al-consumidor-una-prioridad-plataforma-en-chile-coordina-6-pa-ses' },
// { URL: 'https://www.cocacoladechile.cl/novedades/innovacion-apet-un-equipo-de-lujo-liderado-por-una-mujer' },
// { URL: 'https://www.cocacoladechile.cl/novedades/innovacion-las-lecciones-de-ecodiseno-de-oscar-huerta' },
// { URL: 'https://www.cocacoladechile.cl/novedades/innovacion-ecodisenar-en-el-desierto' },
// { URL: 'https://www.cocacoladechile.cl/novedades/innovacion-ecodise-o-y-m-s-sabor-la-mejor-innovaci-n' },
// { URL: 'https://www.cocacoladechile.cl/novedades/innovacion-botella-nica-retornable-m-s-conveniente-y-sustentable' },
// { URL: 'https://www.cocacoladechile.cl/novedades/innovacion-ruta-de-envases-retornables' },
// { URL: 'https://www.cocacoladechile.cl/novedades/innovacion-cero-residuos-innovacion-perfecta' },
// { URL: 'https://www.cocacoladechile.cl/novedades/innovacion-embotellado' },
// { URL: 'https://www.cocacoladechile.cl/novedades/historia-del-campo-a-la-convencion-de-coleccionistas-de-coca-cola' },
// { URL: 'https://www.cocacoladechile.cl/novedades/historia-una-manana-en-la-fabrica-de-la-felicidad' },
// { URL: 'https://www.cocacoladechile.cl/novedades/history-richi-meza-buscador-de-tesoros' },
// { URL: 'https://www.cocacoladechile.cl/novedades/history-asi-nacio-el-sabor-que-nos-refresca' },
// { URL: 'https://www.cocacoladechile.cl/novedades/history-130-anos-de-eslogans-la-historia-en-una-frase' },
// { URL: 'https://www.cocacoladechile.cl/novedades/nuestra-gente-el-liderazgo-femenino-en-la-moderna-linea-apet' },
// { URL: 'https://www.cocacoladechile.cl/novedades/nuestra-gente-padre-e-hija-al-servicio-de-la-educacion-creativa' },
// { URL: 'https://www.cocacoladechile.cl/novedades/nuestra-gente-stor-vidal-le-he-ganado-a-la-adversidad' },
// { URL: 'https://www.cocacoladechile.cl/novedades/nuestra-gente-de-futbolista-a-trabajador-historico-' },
// { URL: 'https://www.cocacoladechile.cl/novedades/gente-entre-flashes-y-camaras' },
// { URL: 'https://www.cocacoladechile.cl/novedades/gente-una-vida-de-alto-rendimiento' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-coca-cola-lanza-un-mundo-sin-residuos-en-chile' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-patricia-aliaga--orgullosa-recicladora-de-base' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-brota-la-esperanza-en-santa-olga' },
// { URL: 'https://www.cocacoladechile.cl/novedades/mar-a-teresa-ruiz-la-humanidad-no-puede-despilfarrar-el-aporte-de-las-mujeres' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-yanet--la-reina-de-las-botellas-plasticas' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-zero-waste-de-coca-cola-andina-la-tarea-bien-hecha' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-limpiar-playas-para-cambiar-la-herencia' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-fundacion-coca-cola-llego-a-u-1-000-millones-en-donaciones' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-celebramos-los-10-anos-de-5by20-con-un-webinar-de-lujo-' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-negocios-prosperos' },
// { URL: 'https://www.cocacoladechile.cl/novedades/innovacion-wabi--tecnologia-para-reconectar-a-los-almaceneros-con-sus-clien' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-botellas-100-reciclable' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-progresos-en-el-camino-hacia-un-mundo-sin-residuos-' },
// { URL: 'https://www.cocacoladechile.cl/novedades/productos-vivamos-mas-retornable' },
// { URL: 'https://www.cocacoladechile.cl/novedades/impacto-socio-economico' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-salvador-allendes-con-recicla-en-casa-mi-situaci-n-cambi-un-100' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-vecinos-de-majada-blanca-vuelven-a-tener-agua-es-dignidad' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-marta-zapata-almacenera-la-mujer-pone-la-fuerza-para-sacar-adelante-a-su-familia' },
// { URL: 'https://www.cocacoladechile.cl/novedades/empaques-sustentables-botellas-plasticas-que-se-transforman-en-mochilas' },
// { URL: 'https://www.cocacoladechile.cl/novedades/al-rescate-de-el-morado-y-rio-clarillo' },
// { URL: 'https://www.cocacoladechile.cl/novedades/historias-bienestar-una-visita-al-futuro' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-ihabemus-agua--cuatro-localidades-afectadas-por-la-megasequia--c' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-reciclador-crea-una-maquina-made-in-chile-para-reutilizar-pallet' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-mas-productividad-con-menos-agua--la-ecuacion-crucial' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-fondo-innova-agua-avanza-10-proyectos-preseleccionados' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-sprite-clear--un-nuevo-y-transparente-comienzo' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-que-es-el-apr-' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-countdown-chile-experiencias-inspiradoras-que-cuidan-el-planeta' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-pobres-de-agua-una-dolorosa-realidad' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-fondo-de-agua-busca-proyectos-innovadores-para-zonas-mas-afectad' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-a-un-ano-del-6d--los-arboles-crecen-sanos-en-el-cerro-renca' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-emotiva-jornada-de-cierre-de-programa-en-almacenes-en-bajos-de-m' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-juntosparaalgomejor-qui-n-dijo-que-tenemos-que-volver-a-lo-normal' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-gerenta-de-acci-n-empresas-persiste-la-idea-de-que-el-empleo-femenino-es-accesorio' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-como-seguir-integrando-a-las-mujeres-al-mercado-laboral-' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-gerente-de-krossbar-decidimos-aguantar-y-vali-la-pena-la-espera' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-2020-un-a-o-en-el-que-juntoshicimosladiferencia' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-como-sera-esta-navidad-para-los-chilenos-' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-mujeres-de-san-joaquin-distribuyen-cenas-solidarias-de-navidad' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-ministra-zalaquett-es-imposible-reactivar-chile-sin-incorporar-a-las-mujeres' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-julieta-mart-nez-l-der-de-tremendas-quiero-cambiar-el-mundo' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-_justo_--el-delivery-de-juntos-en-todas' },
// { URL: 'https://www.cocacoladechile.cl/novedades/productos-javier-meza--_juntos-para-algo-mejor-es-genuino-a-la-marca' },
// { URL: 'https://www.cocacoladechile.cl/novedades/productos-coleccionistas-de-coca-cola-organizan-encuentro-virtual-ni-el-coronavirus-nos-detiene' },
// { URL: 'https://www.cocacoladechile.cl/novedades/productos-conoce-las-tres-variedades-de-topo-chico-hard-seltzer0' },
// { URL: 'https://www.cocacoladechile.cl/novedades/productos-topo-chico-hard-seltzer-desembarca-en-chile' },
// { URL: 'https://www.cocacoladechile.cl/novedades/productos-la-navidad-de-los-coleccionistas-de-coca-cola' },
// { URL: 'https://www.cocacoladechile.cl/novedades/productos-que-es-una-bebida-hard-seltzer-' },
// { URL: 'https://www.cocacoladechile.cl/novedades/productos-el-viejito-pascuero-esta-llamando' },
// { URL: 'https://www.cocacoladechile.cl/novedades/innovacion-el-_heroe-del-planeta--orador-estrella-del-congreso-futuro-2021' },
// { URL: 'https://www.cocacoladechile.cl/novedades/innovacion-j-venes-protagonizan-el-congreso-futuro-2021-a-n-podemos-so-ar' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-reforzamos-nuestro-compromiso-con-la-paridad-de-genero' },
{ URL: 'https://www.cocacoladechile.cl/novedades/comunidad-cuatro-consejos-para-potenciar-el-delivery-del-almacen' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-_conecta--recicla-y-colabora--nueva-iniciativa-para-incentivar-r' },
{ URL: 'https://www.cocacoladechile.cl/novedades/comunidad-coca-cola-chile-lanza-el-sabor-de-compartir-en-comedor-social-de' },
// { URL: 'https://www.cocacoladechile.cl/novedades/carbon--carne--empanadas-y-bebidas--todo-para-la-celebracion-die' },
// { URL: 'https://www.cocacoladechile.cl/novedades/conecta--recicla-y-colabora--recicladores-del-barrio-yungay-mult' },
// { URL: 'https://www.cocacoladechile.cl/novedades/alejandro--almacenero-en-modo-dieciochero--ibrindo-por-las-retor' },
// { URL: 'https://www.cocacoladechile.cl/novedades/academia-coca-cola--un-nuevo-impulso-para-los-almaceneros-de-chi' },
// { URL: 'https://www.cocacoladechile.cl/novedades/nace-la-primera--escuela-de-lluvia--en-chile-' },
// { URL: 'https://www.cocacoladechile.cl/novedades/daniel-mena--almacenero-de-la-academia-coca-cola---la-recomiendo' },
// { URL: 'https://www.cocacoladechile.cl/novedades/de-la-semilla-al-plato--mano-de-chef-es-parte-de-el-sabor-de-com' },
// { URL: 'https://www.cocacoladechile.cl/novedades/un-18-especial-con-comida-para-todos' },
// { URL: 'https://www.cocacoladechile.cl/novedades/el-legado-familiar-que-se-potencio-con-la-academia-coca-cola' },
// { URL: 'https://www.cocacoladechile.cl/novedades/mujeres-circulares--el-dialogo-que-busca-mejorar-relacion-con-lo' },
// { URL: 'https://www.cocacoladechile.cl/novedades/trabajar-mas-y-mejor--recicladores-de-quilicura-cuentan-ahora-co' },
// { URL: 'https://www.cocacoladechile.cl/novedades/vanessa--una-almacenera-que-suena-en-grande---queremos-que-este-' },
// { URL: 'https://www.cocacoladechile.cl/novedades/localshop--el-delivery-que-reactiva-el-barrio' },
// { URL: 'https://www.cocacoladechile.cl/novedades/un-nuevo-impulso-para-esta-familia-de-recicladores-de-estacion-c' },
// { URL: 'https://www.cocacoladechile.cl/novedades/nelson--conductor-todoterreno---lo-que-he-logrado-es-gracias-a-c' },
// { URL: 'https://www.cocacoladechile.cl/novedades/un-almacen-familiar-que-crece-gracias-a-la-academia-coca-cola' },
// { URL: 'https://www.cocacoladechile.cl/novedades/1ko--la-comunidad-de-talentos-que-busca-unir-mundos' },
// { URL: 'https://www.cocacoladechile.cl/novedades/la-cava-del-sommelier--restaurante-escuela-de-los-boot-camps-de-' },
// { URL: 'https://www.cocacoladechile.cl/novedades/proyecto-nilus--glaciares-artificiales-que-almacenan-agua' },
// { URL: 'https://www.cocacoladechile.cl/novedades/sara-soto--tejedora-del-proyecto-1ko---este-trabajo-ha-sido-nues' },
// { URL: 'https://www.cocacoladechile.cl/novedades/ana--tejedora-de-1ko---sentimos-que-estamos-vivos--ahora-tenemos' },
// { URL: 'https://www.cocacoladechile.cl/novedades/bootcamps--una-alianza-virtuosa-para-que-jovenes-en-situacion-de' },
// { URL: 'https://www.cocacoladechile.cl/novedades/-mi-barrio--mi-almacen---billeteras-digitales-para-vecinos-de-re' },
// { URL: 'https://www.cocacoladechile.cl/novedades/en-el-dia-mundial-del-agua-coca-cola-renueva-su-compromiso' },
{ URL: 'https://www.cocacoladechile.cl/novedades/comunidad-nace-prospera--el-ambicioso-programa-integral-para-almacenes' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-la-tecnologia-que-cambiara-a-23-almacenes-' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comenzaron-los-bootcamps--asi-aprenden-en-el-munich-de-malloco' },
// { URL: 'https://www.cocacoladechile.cl/novedades/el--ceachei--del-supervisor-de-coca-cola-tras-correr-la-maraton-' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-emotiva-jornada-de-cierre-de-programa-en-almacenes-en-bajos-de-m1' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-la-ruta-del-reciclaje-de-botellas-en-santiago-poniente' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-con-agua-limpia-y-segura--comienza-una-nueva-era-en-villa-peldeh' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-la-ruta-de-camila--una-mujer-que-trabaja-para-impulsar-a-los-alm' },
{ URL: 'https://www.cocacoladechile.cl/novedades/comunidad-almaceneros-se-capacitan-para-hacer-delivery' },
// { URL: 'https://www.cocacoladechile.cl/novedades/empaques-sustentables-retornables-la-nueva-opci-n-para-clientes-de-oxxo' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-por-que-la-botella-transparente-es-mas-amigable-con-el-medio-am' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-xito-total-600-ni-as-de-toda-latinoam-rica-comienzan-su-participaci-n-en-la-academia-clim-ticas' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-mitos-y-verdades-de-los-envases-retornables' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-paula-l-pez-vendedora-de-coca-cola-tengo-la-pega-ideal' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-daniel-se-capacita-para-gestionar-mejor-su-local-prospera-me-lleg-del-cielo' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-familia-de-almaceneros-prospera-es-como-un-tesoro' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-radiografia-de-los-dos-primeros-anos-del-pacto-chileno-de-los-pl' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-julio-flores--el-profe-de-prospera' },
// { URL: 'https://www.cocacoladechile.cl/novedades/carmen-y-su-experiencia-en-clim-ticas-queremos-formar-un-equipo-entre-todas' },
// { URL: 'https://www.cocacoladechile.cl/novedades/dejar-un-legado-a-las-nuevas-generaciones--el-objetivo-de-eduard' },
// { URL: 'https://www.cocacoladechile.cl/novedades/-la-navidad-es-magica-cuando-la-compartimos---conoce-nuestra-cam' },
// { URL: 'https://www.cocacoladechile.cl/novedades/el-bus-de-la--roja--acompano-a-las-artesanas-de-1ko-a-la-enade-2' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-directora-de-proyectos-de-amul-n-el-acceso-al-agua-tiene-el-poder-de-cambiar-la-vida-de-las-personas' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-agua-de-lluvia-en-linda-vista-nos-est-n-haciendo-felices-a-todos' },
// { URL: 'https://www.cocacoladechile.cl/novedades/innovacion-coca-cola-andina--20-anos-trabajando-en-electromovilidad' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-desaf-oretornables-envases-100-sustentables' },
{ URL: 'https://www.cocacoladechile.cl/novedades/comunidad-_el-sabor-de-compartir-llego-a-bajos-de-mena' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-yolanda-pizarro-para-tener-un-buen-negocio-las-almaceneras-primero-tienen-que-creer-en-ellas' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-pablo-beas-coach-de-academia-coca-cola-vamos-a-ense-ar-a-los-almaceneros-a-vender-m-s-y-mejor' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-brecha-h-drica-qu-es-y-c-mo-afecta-el-desarrollo-de-las-comunidades' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-edita-orellana-almacenera-gracias-al-cari-o-de-mis-vecinos-he-salido-adelante' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-melyna-montes-la-mujer-tiene-el-poder' },
// { URL: 'https://www.cocacoladechile.cl/novedades/comunidad-desde-su-almacen--alejandra-transforma-a-su-comunidad' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-imas-puntos-limpios-para-santiago--ahora-podras-reciclar-en-oxxo' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-pablo-cassorla--el-ingeniero-que-mejora-el-acceso-al-agua' },
// { URL: 'https://www.cocacoladechile.cl/novedades/el-coleccionista-de-curico-que-termino-trabajando-en-coca-cola' },
// { URL: 'https://www.cocacoladechile.cl/novedades/una-dupla-de-almaceneros-que-cumplieron-el-sueno-de-emprender' },
{ URL: 'https://www.cocacoladechile.cl/novedades/comunidad-coca-cola-chile-y-academia-emprende-banco-estado-se-unen-para-ca' },
// { URL: 'https://www.cocacoladechile.cl/novedades/poleras-_fashion-hechas-con-botellas-recicladas' },
// { URL: 'https://www.cocacoladechile.cl/novedades/la-mejor-coca-cola-de-todas' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-academia-climaticas-y-coca-cola-celebraron-dia-mundial-del-recic' },
// { URL: 'https://www.cocacoladechile.cl/novedades/-y-si-por-cada-comida-que-compras-pudieras-apoyar-a-alguien-que-' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-academia-clim-ticas-x-tremendas-jesse-y-camila-cuidan-el-planeta-desde-sus-regiones' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-agua-de-lluvia-para-todos-los-dias' },
{ URL: 'https://www.cocacoladechile.cl/novedades/comunidad-la-cadena-solidaria-de-comida-para-todos-' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-rembre-las-claves-de-un-exitoso-modelo-de-gesti-n-de-residuos' },
{ URL: 'https://www.cocacoladechile.cl/novedades/comunidad-restaurante-verso--eslabon-de-la-cadena-virtuosa-de-el-sabor-de-' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-hermanas-garcia--dos-jovenes-graduadas-de-academia-climaticas' },
{ URL: 'https://www.cocacoladechile.cl/novedades/comunidad-elsabordecompartir-un-techo-fraterno-en-tiempos-de-pandemia' },
{ URL: 'https://www.cocacoladechile.cl/novedades/comunidad-_la-caperucita-y-el-lobo-entrega-almuerzos-junto-a-el-sabor-de-c' },
// { URL: 'https://www.cocacoladechile.cl/novedades/sprite--del-compromiso-a-la-accion' },
// { URL: 'https://www.cocacoladechile.cl/novedades/premio-a-la-innovacion-sustentable' },
// { URL: 'https://www.cocacoladechile.cl/novedades/jovenes-de-los-andes-viven-su-propio-bootcamp-' },
// { URL: 'https://www.cocacoladechile.cl/novedades/con-ustedes--los-bootcamps-gastronomicos' },
// { URL: 'https://www.cocacoladechile.cl/novedades/desafios-en-sustentabilidad--representantes-de-chile-en-la-cop26' },
// { URL: 'https://www.cocacoladechile.cl/novedades/summit-internacional-mujeres-y-negocios-2021-destaco-el-rol-de-c' },
// { URL: 'https://www.cocacoladechile.cl/novedades/cocinar-para-otros--un-acto-de-amor-en-navidad' },
// { URL: 'https://www.cocacoladechile.cl/novedades/el-live-de-instagram-que-enseno-a-transformar-las-sobras-naviden' },
// { URL: 'https://www.cocacoladechile.cl/novedades/bootcamps-gastronomicos-se-consolidan-como-aliados-de-los-suenos' },
// { URL: 'https://www.cocacoladechile.cl/novedades/navidad-solidaria--coca-cola-y-comida-para-todos-se-unen-nuevame' },
// { URL: 'https://www.cocacoladechile.cl/novedades/un-almuerzo-compartido--la-celebracion-navidena-de-comida-para-t' },
// { URL: 'https://www.cocacoladechile.cl/novedades/reducir--reutilizar-y-reciclar--pilares-de-la-cumbre-sustentable' },
// { URL: 'https://www.cocacoladechile.cl/novedades/medio-ambiente-radiografia-de-los-dos-primeros-anos-del-pacto-chileno-de-los-pl1' },
// { URL: 'https://www.cocacoladechile.cl/novedades/conecta--recicla-y-colabora--mas-equipados-para-recolectar-botel' },
// { URL: 'https://www.cocacoladechile.cl/novedades/coca-cola-chile-y-comida-para-todos--una-alianza-con-resultados-' },
];

function getEntries(locale) {
  switch (locale) {
    case 'bo':
      return bo;
    case 'cl':
      return cl;
    default:
      return [];
  }
}

export default getEntries;
