/*
 * Copyright 2020 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

function getEntries() {
  return [
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/bienestar-la-reduccion-calorica-en-nuestras-bebidas-es-la-prioridad-del-n' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/ecoladrillos-para-viviendas-sustentables--el-sueno-de-david-para' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/bienestar-conoce-como-trabaja-el-centro-de-innovacion' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/bienestar-de-la-f-brica-a-la-mesa-coca-cola-apuesta-por-las-compras-online-y-el-delivery-seguro-con-su-nueva-plataforma-de-ventas' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-asi-funcionan-los-acuerdos-reciprocos-por-agua-que-salvan-bosques' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-coca-cola-renueva-su-compromiso-con-bolivia-en-su-196-aniversari' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-el-compromiso-por-unmundosinresiduos-suma-nuevos-aliados-en-lago-titicaca' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-el-primer-concurso-de-poesia-sobre-reciclaje-ya-tiene-ganadora' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-conocemos-a-claudia--la-primera-chofer-de-coca-cola-bolivia-' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-la-plataforma-de-educacion-ambiental-re-crea-ya-capacito-a-1-200' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/impacto-socio-economico' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-coca-cola-bolivia-suma-una-nueva-alianza-para-avanzar-en-el-cami' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-coca-cola-bolivia-refuerza-su-compromiso-por-un-mundo-sin-residuos-con-la-botella-de-vital-hecha-100-de-otras-botellas' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-por-qu-decirle-que-s-a-las-botellas-retornables-la-respuesta-est-en-las-cuatro-r-de-la-retornabilidad' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-fundacion-ellen-macarthur--los-plasticos-dentro-de-la-economia-y' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-este-22-de-marzo-reafirmamos-nuestro-compromiso-con-el-cuidado-d' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-nuestro-compromiso--optimizar-el-uso-de-agua' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-emprendedoras-bolivianas-se-capacitan-para-mejorar-sus-negocios' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-objetivo-logrado-coca-cola-bolivia-celebra-la-participaci-n-de-m-s-de-4-000-emprendedores-en-los-programas-gerente-pyme' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-_semilla-capital-2-0-ipara-crecer-juntos--llegaa-a-ocho-ciudades' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-la-fundacion-coca-cola-llego-a-u-s1-000-millones-en-donaciones' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/-salteneria-chingola---tradicion-familiar-atras-de-la-empanada-r' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/fundacion-coca-cola-de-bolivia-recibe-el--reconocimiento-a-la-re' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/la-red-de-contenedores-para-reciclar-llego-a-mercados-y-centros-' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/conexiones--la-exposicion-fotografica-que-enaltece-el-trabajo-de' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/te-contamos-la-rica-historia-detras-de-la-saltena--este-simbolo-' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/foro-latinoamericano-de-economia-circular--compartimos-los-avanc' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/seguimos-acompanando-a-las-emprendedoras-bolivianas--800-mujeres' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/-la-navidad-es-magica-cuando-la-compartimos---conoce-la-campana-' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-sabor-y-tradicion--el-exito-detras-del-restaurante-la-le-li-lo-l' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-nos-sumamos-a-la-campana-global-de-plan-international-para-empod' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-la-cocina-de-_aurorita-nos-abre-sus-puertas-y-devela-el-secreto-' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-elmejorregaloserest-conoce-a-los-emboluntarios-que-alegraron-las-fiestas-a-los-ni-os-del-hogar-francisca-risci' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-juntossalimosadelante-trabajadores-de-cuatro-hospitales-de-bolivia-recibieron-donaciones-de-equipos-de-bioseguridad' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-coca-cola-bolivia-y-pnud-renuevan-su-alianza-para-apoyar-la-reac' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-la-salte-er-a-jet-set-tradici-n-cultura-y-una-invitaci-n-a-hacer-especial-cualquier-d-a-de-la-semana' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-tienen-tres-restaurantes-a-cargo-y-enfrentaron-la-pandemia-a-fue' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-animate-a-preparar-compost-casero-con-cuatro-sencillos-pasos-' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-primitivo-quispe--el-guia-que-suena-con-seguir-amaneciendo-entre' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-liliana-emprendedora-de-calidad-a-los-21-a-os-abri-su-propia-tienda-y-hoy-se-capacita-para-hacer-crecer-su-negocio' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-san-felix-cuida-su-tesoro-mas-preciado-y-mejora-el-acceso-a-agua' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-dannya--la-sonadora-que-construyo-de-cero-su-propio-micromercado' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-san-jacinto-se-convierte-en-un-modelo-de-gestion-de-agua-en-la-r' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-basilia-lidera-el-negocio-turistico-familiar-y-cuida-los-bosques' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-diez-nuevos-contenedores-para-botellas-pet-dan-nuevo-impulso-al-' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-ser-transparente-para-ser-m-s-verde-sprite-clear-m-s-amigable-con-el-ambiente' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-el-reciclaje-y-la-solidaridad-se-alian-en-tarija-de-la-mano-de-v' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-los-contenedores-de-reciclaje-de-vital-llegan-a-mas-ciudades-de-' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-los-envases-de-pet-transparente--aliados-en-la-industria-de-la-e' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-primitivo-quispe--el-guia-que-suena-con-seguir-amaneciendo-entre1' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/bienestar-fanta-se-vuelve-loca-de-colores-para-desterrar-los-dias-grises' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/retornar-en-algo-mejor--el-nuevo-comercial-de-coca-cola-que-insp' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-agrupaciones-de-recolectores-reciben-nueve-flamantes-motocarros-' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-lonas-publicitarias-recicladas-se-convierten-en-ecobolsos-' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-alfabeto--la-divertida-propuesta-de-coca-cola-para-que-compartas' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-te-presentamos-a-la-multifac-tica-karina-recolectora-l-der-gremial-y-madre-de-cinco-hijos' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-lasmujerestransforman-acompa-amos-el-desarrollo-econ-mico-de-5-millones-de-mujeres-y-renovamos-nuestro-compromiso' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-luchadora-y-comprometida-te-presentamos-a-mar-a-teresa-la-mujer-que-lidera-la-fundaci-n-natura-y-transforma-su-comunidad' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-lasmujerestransforman-j-venes-y-preparadas-el-nuevo-perfil-de-la-emprendedora-boliviana' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/-lasmujerestransforman-para-crear-un-mundo-mejor' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-nuestro-homenaje-a-los-padres-emprendedores--que-con-su-fuerza-y' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-alejandro-soto-un-agricultor-comprometido-con-el-planeta-y-sus-vecinos-ofreci-la-vertiente-que-nace-en-sus-tierras-para-abastecer-de-agua-a-la-comunidad' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-las-fabricas-de-agua-de-la-fundacion-natura-son-reconocidas-mund' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-un-mundo-sin-residuos-los-contenedores-de-reciclaje-de-vital-llegan-a-sucre' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-empacar-suma-energia-solar-a-su-planta-de-reciclaje-y-se-consoli' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-los-contenedores-de-reciclaje-de-vital-llegan-a-las-provincias-d' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-detr-s-de-la-idea-conocemos-a-los-creativos-responsables-de-la-nueva-campa-a-de-coca-cola-bolivia-que-promueve-los-envases-retornables' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/el-esp-ritu-del-compromiso-por-un-unmundosinresiduos-desembarca-en-el-lago-uru-uru-de-oruro' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-los-contenedores-de-reciclaje-de-vital-llegan-a-estaciones-de-se' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-santa-cruz-impulsa-el-reciclaje-y-el-trabajo-de-los-recolectores' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-encuentro-de-intercambio-verde-una-experiencia-para-unir-esfuerzos-por-unmundosinresiduos' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-recolectores-de-santa-cruz-reciben-compactadoras-de-botellas-y-c' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad------_la-casona_--el-restaurante-familiar-que-celebra-el-apoyo-d' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-d-a-de-la-tierra-2021-reafirmamos-nuestro-trabajo-en-el-cuidado-del-planeta' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-daniela--la-especialista-medioambiental-que-busca-empoderar-a-lo' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-claudia--la-chofer-de-coca-cola-que-con-su-tiktok-ayuda-a-cuidar' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-cuidar-al-medio-ambiente-impulsar-a-las-mujeres-y-trabajar-junto-a-las-comunidades-los-hitos-de-los-78-a-os-de-coca-cola-bolivia' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/coca-cola-bolivia-junto-a-la-fundacion-alalay-y-los-restaurantes-del-pais-se-unen' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-conocemos-a-los-vecinos-del-condominio-vittoria--un-ejemplo-en-e' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-cleider-y-ciro-recolectores-de-base-es-una-emoci-n-ayudar-a-que-nuestro-hijo-cumpla-su-sue-o-de-ser-piloto' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-te-invitamos-a-conocer-el-proyecto-recrea--nuestra-iniciativa-pa' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-mas-de-120-trabajadores-de-la-embotelladora-embol-celebraron-el-' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-dise-o-ecol-gico-y-solidario-transforman-lonas-publicitarias-recicladas-en-impermeables-para-personas-sin-hogar' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/productos-la-nueva-coca-cola-sin-az-car-llega-a-bolivia-con-un-desaf-o-es-la-mejor-coca-cola-de-todas' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-el-periodismo-verde-gana-terreno-conocemos-el-trabajo-de-la-uni-n-de-periodistas-ambientales-de-bolivia' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-se-presento-latitud-r--la-plataforma-que-busca-transformar-la-ge' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-sumate-al-desafio-retornable-y-cuida-el-planeta-' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-puerta-a-puerta-por-un-mundo-sin-residuos-recolectores-de-santa-cruz-entusiasman-a-los-vecinos-para-impulsar-el-reciclaje' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-seis-de-cada-diez-bolivianos-ya-eligen-sus-bebidas-favoritas-en-botellas-retornables-conoce-por-qu-y-s-mate-t-tambi-n' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-y-si-por-cada-comida-que-compras-pudieras-donar-otra-para-algui' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-veronica-virreira-resignifica-el-plastico-de-descarte-y-los-tran' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-retornables-y-recuperaci-n-de-envases-coca-cola-bolivia-y-su-compromiso-con-la-econom-a-circular' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-reciclaje-y-compostaje--los-dos-caminos-para-contribuir-desde-ca' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/historia-rogelio--el-sonador-que-paso-de-ayudante-a-propietario-de-dos-ca' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-superior-taste-award-2021-vital-fue-catalogada-como-sobresaliente-por-un-jurado-de-200-chefs-y-sommeliers' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente--los-que-vivimos-del-campo-sabemos-la-importancia-del-agua-y-la-' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidadnos-sumamos-a-la-campana-ninas-con-igualdad' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-mas-de-100-familias-de-los-yungas-tendran-acceso-a-agua-potable-' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-coca-cola-y-el-agua-en-am-rica-latina-cuando-las-personas-se-sienten-parte-de-la-soluci-n-todo-toma-fuerza' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-el-compromiso-por-el-medio-ambiente-volvio-a-unir-a-los-trabajad' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad--_mi-sueno-era-tener-esta-casa-de-huespedes--te-presentamos-a-ma' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-emprendedores-turisticos-de-tihuanaco-apuestan-por-la-biosegurid' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-fundacion-coca-cola-suma-su-apoyo-para-que-1-100-hogares-del-pai' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-el-compromiso-por-unmundosinresiduos-se-suma-a-la-expocruz-la-feria-m-s-importante-de-bolivia' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-expocruz-2021--un-gran-espacio-de-reencuentro-para-promover-la-r' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-objetivo-cumplido-1-000-contenedores-de-reciclaje-de-vital-ya-est-n-instalados-en-diferentes-puntos-de-bolivia' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/juntos-para-algo-mejor-el-mensaje-de-coca-cola-para-ver-el-mundo-com-optimismo' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-el-alto--pando-y-beni-se-suman-a-la-red-de-contenedores-de-recic' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/comunidad-en-el-dia-de-la-mujer-boliviana--celebramos-a-aquellas-que-lider' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-los-contenedores-de-reciclaje-de-vital-son-un-xito-en-las-estaciones-de-servicio-de-santa-cruz-recolectan-1-200-kilos-de-botellas-al-mes' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-la-escuela-de-los-acuerdos-reciprocos-por-agua-capacita-a-repres' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-las-familias-de-miraflores--guardianas-de-los-bosques--se-encami' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/iliana-reza--vicepresidente-de-operaciones-de-coca-cola-para-el-' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/cuidar-el-agua-y-mejorar-su-acceso-en-comunidades-rurales-de-bol' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/el-2021--un-ano-en-el-que-juntos-logramos-grandes-avances-en-el-' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/jenny--un-ejemplo-de-pujanza-al-frente-de-su-emprendimiento-gast' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/repasemos-juntos-nuestro-trabajo-de-2021--un-ano-lleno-de-desafi' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/pacto-global-reconoce-nuestras-buenas-practicas-en-materia-de-de' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/cuidar-el-agua-y-mejorar-su-acceso-en-comunidades-rurales-de-bol0' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/el-2021--un-ano-en-el-que-juntos-logramos-grandes-avances-en-el-0' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-se-presento-latitud-r--la-plataforma-que-busca-transformar-la-ge1' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/medio-ambiente-sumate-al-desafio-retornable-y-cuida-el-planeta-1' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/gerente-pyme-y-semilla-capital-volvieron-a-hacer-la-diferencia-p' },
    { URL: 'https://www.coca-coladebolivia.com.bo/novedades/ecoladrillos-para-viviendas-sustentables--el-sueno-de-david-para' },
  ];
}

export default getEntries;
