name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run:
      name: configure git auth
      command: git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf https://github.com/
    - run:
      name: configure npm registry
      command: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
    - run: npm install
      working-directory: test
    - run: npm run lint
    - run: npm test
      working-directory: test
      env:
        CI: true